version: "3"

networks:
  monitoring:
    driver: bridge





services:
    api:
        container_name: api
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db

    db:
        container_name: db
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1435:1433"

        environment:
            
            SA_PASSWORD: "12345Aa!"
            ACCEPT_EULA: "Y"

    node-exporter:
      image: prom/node-exporter:latest
      container_name: node-exporter
      restart: unless-stopped
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
      expose:
        - 9100
      networks:
        - monitoring

    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      restart: unless-stopped
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
      expose:
        - 9090
      networks:
        - monitoring